# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe2ac6cf1b6aa2c429893446298015b95e6d1f682a7a6f4b8f6cb3aaee619717e6a793b6a1a5b47618818933266bd12babc1c5e283eba406afeb917b632debf7

test:
  secret_key_base: 5fba99a477cafe86f9b9aadb82ffef8c6237d7b5165925b1f16e27676d314422ef58f20a16a3344d784bec64fbb0246d1617797461e6bcf0a0399613e01c2cfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
